{% set name = "mysql-connector-cpp" %}
{% set url_name = "mysql-connector-c++" %}
{% set version = "8.0.29" %}
{% set build_number = 3 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dev.mysql.com/get/Downloads/Connector-C++/{{ url_name|lower }}-{{ version }}-src.tar.gz
  sha256: 9a6236a28bca33ae951d8ccaabb8ff51a188863e8599f9096f4ae0a1da19f87f
  patches:
    - patches/0001-Override-custom-install-layout.patch
    - patches/0002-cmake-libutils-add-support-for-using-Ninja-VS.patch
    - patches/0003-Define-helper-vars-for-cross-compilation.patch
    - patches/0004-Relax-constraint-on-OpenSSL-version.patch

build:
  skip: true  # [win and vc<14]
  number: {{ build_number }}
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]
  ignore_run_exports:
    # Only headers are required, license is same
    - mysql-libs

requirements:
  build:
    - cmake
    - make   # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - openssl
    # The following are required only if JDBC support is enabled
    - libboost-headers
    - mysql-devel {{ version }}
    - zlib
    - zstd

test:
  files:
    - cmake_test             # [unix]
  requires:
    - cmake                  # [unix]
    - make                   # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('c') }}    # [unix]
  commands:
    - test -f "${PREFIX}/include/mysqlx/common.h"             # [unix]
    - test -f "${PREFIX}/include/mysqlx/devapi/collations.h"  # [unix]
    - test -f "${PREFIX}/lib/libmysqlcppconn8${SHLIB_EXT}"    # [unix]
    - if not exist %LIBRARY_INC%\mysqlx\common.h            exit 1  # [win]
    - if not exist %LIBRARY_INC%\mysqlx\devapi\collations.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\mysqlcppconn8.lib          exit 1  # [win]
    - if not exist %LIBRARY_LIB%\mysqlcppconn8-static.lib   exit 1  # [win]
    - if not exist %LIBRARY_BIN%\mysqlcppconn8-2-vs14.dll   exit 1  # [win]
    - cmake -Scmake_test -Bcmake_test/build                   # [unix]

about:
  home: https://dev.mysql.com/doc/connector-cpp/8.0/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: MySQL Connector/C++, the C++ interface for communicating with MySQL servers.
  description: |
    MySQL Connector/C++ 8.0 is a MySQL database connector for C++ applications
    that connect to MySQL servers.

extra:
  recipe-maintainers:
    - nehaljwani
